[workspace]
resolver = "2"
members = ["guest", "host"]
default-members = ["host"]

[workspace.dependencies]
jolt-sdk = { git = "https://github.com/a16z/jolt" }
ark-serialize = "0.5.0"
revm-guest = { path = "./guest" }

[profile.release]
debug = 1
codegen-units = 1
lto = "fat"

[patch.crates-io]
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
radium = { git = "https://github.com/ferrilab/ferrilab", package = "radium", rev = "3fdd72f3286110b1958f020b984999326190f42f" }
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", tag = "patch-0.30.0-sp1-4.2.0" }
