[workspace]
resolver = "2"
members = ["guest", "host"]
default-members = ["host"]

[workspace.dependencies]
jolt-sdk = { git = "https://github.com/a16z/jolt" }
ark-serialize = "0.5.0"
revm-guest = { path = "./guest" }

[profile.release]
debug = 1
codegen-units = 1
lto = "fat"

[patch.crates-io]
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }