[package]
name = "revm-host"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
revm-guest = { workspace = true }

[features]
icicle = ["jolt-sdk/icicle"]
