[package]
name = "revm-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt-sdk = { workspace = true }
revm = { workspace = true, features = ["serde"] }
getrandom = { workspace = true, features = ["custom"] }
once_cell = { workspace = true, features = ["critical-section"] }
portable-atomic = { workspace = true, features = ["critical-section"] }
critical-section = { workspace = true }
serde = { workspace = true, features = ["derive"] }
