#!/bin/bash

git config --global --add safe.directory $(pwd)/
cargo install cargo-nextest	

apt-get update && apt-get install -y --no-install-recommends gh device-tree-compiler

if ! gh auth status >/dev/null 2>&1; then \
    echo "GitHub authentication required. Please login:"; \
    gh auth login; \
fi

mkdir -p /opt/riscv/
gh release download --clobber spike-1.1.1 --repo LayerResearch/jolt-revm --pattern "spike-1.1.1-$(uname -s)-$(uname -m).tar.gz" -O /tmp/spike.tar.gz && tar -xzf /tmp/spike.tar.gz -C /opt/riscv/
gh release download --clobber sail-riscv-0.7 --repo LayerResearch/jolt-revm --pattern "sail-riscv-0.7-$(uname -s)-$(uname -m).tar.gz" -O /tmp/sail.tar.gz && tar -xzf /tmp/sail.tar.gz -C /opt/riscv/

# Clone the execution-spec-tests repository and checkout the static tests
pushd overrides
git clone --depth 1 --no-checkout --filter=blob:none https://github.com/ethereum/execution-spec-tests.git execution-spec-tests
cd execution-spec-tests
git sparse-checkout init
git sparse-checkout set --no-cone tests/static
git checkout
popd
